services:
  commerce:
    image: dhi.io/postgres:18-debian13-dev
    environment:
      POSTGRES_USER: mhmod
      POSTGRES_DB: commerceDb
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - '5432:5432'
